#    ______   _______   _______   ______  ________
#   /      \ |       \ |       \ |      \|        \
#  |  $$$$$$\| $$$$$$$\| $$$$$$$\ \$$$$$$ \$$$$$$$$
#  | $$  | $$| $$__| $$| $$__/ $$  | $$     | $$
#  | $$  | $$| $$    $$| $$    $$  | $$     | $$
#  | $$  | $$| $$$$$$$\| $$$$$$$\  | $$     | $$
#  | $$__/ $$| $$  | $$| $$__/ $$ _| $$_    | $$
#   \$$    $$| $$  | $$| $$    $$|   $$ \   | $$
#    \$$$$$$  \$$   \$$ \$$$$$$$  \$$$$$$    \$$

# Database Configuration
database:
  # Database type (mysql or sqlite)
  type: sqlite

  # MySQL Configuration (only used if type = mysql)
  mysql:
    host: localhost
    port: 3306
    database: essentials
    username: root
    password: password

chat:
  default-format: "<white>{player}: <gray>{message}"

  group-formats:
    default: "<white>{player}: <gray>{message}"
    admin: "<red>[Admin] <white>{player}: <gray>{message}"
    moderator: "<blue>[Mod] <white>{player}: <gray>{message}"

# Default Player Settings
default-player-settings:
  # Play sound when using commands
  sounds: true
  # Enables the toggle private messages(msg)
  private-messages: true

# Chat Configuration
chat:
  # Chat format (use %player% for player name, %message% for the message, %prefix% for LuckPerms prefix, %suffix% for LuckPerms suffix)
  format: "<white>%player% <gray>%message%:"

# Warp Configuration
warps:
  # Storage type (yaml or database)
  storage: yaml  
  # Teleport settings
  teleport:
    # Delay in seconds before teleporting (0 to disable)
    delay: 3
    # Cancel teleport if player moves
    cancel-on-move: true

# Home Configuration
homes:
  # Storage type (yaml or database)
  storage: yaml
  # Maximum number of homes a player can have
  max-homes: 3

sounds:
  success:
    sound: BLOCK_NOTE_BLOCK_BIT
    volume: 1.0
    pitch: 1.0
  error:
    sound: BLOCK_NOTE_BLOCK_BIT
    volume: 1.0
    pitch: 0.0
