name: Orbit
version: '1.0'
main: nl.nijhuissven.orbit.Orbit
api-version: '1.21'
authors: [ 'NijhuisSven', 'TheBathDuck' ]
dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: false